/*
 * S5LBox — ARMv6 MMU: virtual-to-physical translation.
 *
 * Implements the ARMv6 short-descriptor translation scheme the ARM1176 uses:
 * a 4096-entry first-level table indexed by VA[31:20], whose entries are either
 * a 1 MB section or a pointer to a 256-entry second-level table indexed by
 * VA[19:12] holding 64 KB large pages or 4 KB small pages. Access is gated by
 * the domain field (via CP15 DACR) and the descriptor's AP bits.
 *
 * Table walks read guest memory through the same bus as everything else, so a
 * page table living in emulated RAM behaves exactly as it would on hardware.
 *
 * The Cortex-A8 profile uses the same walk. ARMv7's short-descriptor format
 * is the ARMv6 extended one (XP=1), which ARMv7 makes the only one: SCTLR.XP
 * and SCTLR.U read as one there and S and R read as zero (exec_cp15_v7),
 * so the legacy subpage and S/R paths below cannot be reached from an ARMv7
 * guest. SCTLR.AFE is bit 29, where the ARM1176 has FA, with the same meaning.
 * TEX remap (SCTLR.TRE) changes only memory types, which nothing here
 * models, and iOS 6's kernel sets neither TRE nor AFE (its SCTLR ORs at
 * 0x800863a4 are U, XP, V, I, Z, W, C and M). The A8 has no PXN and no 40-bit
 * addresses, so an L1 descriptor of type 3 stays a translation fault (as in
 * Unicorn's Cortex-A8) and supersection bits [23:20] and [8:5] are ignored.
 * tools/unicorn_vmsa_diff.py compares these walks, through ATS and PAR,
 * against Unicorn.
 *
 * Copyright (c) 2026 j0shua-SYSON. MIT licensed.
 */
#include "arm.h"
#include <string.h>

/*
 * Pack an ARMv6 fault status register value: status in [3:0], domain in [7:4],
 * and WnR in [11].
 *
 * The rest of the DFSR is deliberately zero, and each zero was checked against
 * what xnu-1357.5.30 actually reads. sleh_abort masks the saved DFSR with
 * 0x40f and tests bit 11 separately, so only three fields reach the kernel:
 *
 *   [3:0]  status — access-flag, translation, domain, and permission faults
 *                    (3/5/6/7/9/b/d/f). sleh_abort branches on all of them.
 *   [10]   status[4], the extended fault codes (TLB conflict, lock abort).
 *                    Nothing in this machine can raise one, so it stays clear.
 *   [11]   WnR     — see below.
 *   [7:4]  domain  — read by nothing in the kernel, but cheap and correct.
 *   [12]   ExT     — external abort qualifier. We have no external abort source:
 *                    an unmapped bus read returns zero rather than signalling,
 *                    so status 0x8/0xc/0xe are unreachable and ExT stays clear.
 *   [1]/status 0b0001 — alignment. XNU clears SCTLR.A and sets SCTLR.U at
 *                    __start+0x16c, so ordinary halfword/word accesses can be
 *                    unaligned while multiple, coprocessor, swap and exclusive
 *                    transfers still fault. Those faults are generated by the
 *                    execution engine before it calls the translator.
 *
 * DFSR[11] ("W: the abort was caused by a write access", DDI0100I) is not
 * optional bookkeeping. XNU's sleh_abort tests it to build the fault_type it
 * hands to arm_fast_fault; with the bit clear, every write fault is repaired as
 * if it were a read, so the PTE is rewritten with AP=0b10 (privileged RW, user
 * read-only) and an unprivileged store faults again on exactly the same
 * instruction, forever.
 *
 * This hid for ~230M instructions of boot because privileged writes are
 * accidentally satisfied by AP=0b10. Only an unprivileged access — STRT/LDRT,
 * or real user mode — can expose it, and the first one the kernel makes is the
 * copyout of "/sbin/launchd" into the pid-1 address space.
 *
 * IFSR has no WnR field, so ARM_ACCESS_FETCH never sets it.
 * (It is fed from this same helper, so a domain also lands in IFSR[7:4]. The
 * ARM1176 documents that field as not meaningful for instruction faults;
 * fleh_prefabt hands the raw IFSR to sleh_abort, which masks it away with
 * 0x40f, so the kernel never sees it either way.)
 */
static inline uint32_t fsr_make(uint32_t status, unsigned domain, bool write) {
    return (status & 0xfu) | ((domain & 0xfu) << 4) | (write ? (1u << 11) : 0u);
}

/*
 * ARM1176 access permissions, including APX (AP[2]) and the deprecated S/R
 * compatibility controls.
 *
 * APX:AP
 *   0:00  no access            0:01  privileged read/write only
 *   0:10  privileged RW, user read-only
 *   0:11  read/write for all
 *   1:00  reserved             1:01  privileged read-only
 *   1:10  read-only for all    1:11  read-only for all (ARM1176-defined)
 *
 * APX must not be ignored: with it dropped, every read-only mapping becomes
 * writable, so a guest kernel's copy-on-write faults and its read-only
 * kernel-text and page-table mappings would silently never fire.
 */
static bool ap_permits(const arm_cpu_t *c, unsigned ap, bool apx,
                       bool write, bool priv) {
    if (apx) {
        switch (ap & 3u) {
            case 0:  return false;              /* reserved */
            case 1:  return priv && !write;     /* privileged read-only */
            default: return !write;             /* read-only for all */
        }
    }
    switch (ap & 3u) {
        case 0: {
            /* APX:AP == 000 normally denies all access. The ARM1176 retains
             * the pre-ARMv6 System/ROM protection escape hatch: R alone makes
             * the mapping read-only for everyone, S alone makes it privileged
             * read-only, and S|R is reserved. These controls apply wherever a
             * descriptor has no APX bit (and to 000 in the extended format). */
            bool s = (c->cp15.sctlr & ARM_SCTLR_S) != 0u;
            bool r = (c->cp15.sctlr & ARM_SCTLR_R) != 0u;
            if (s && r) return false;            /* reserved */
            if (r) return !write;                /* read-only for all */
            if (s) return priv && !write;        /* privileged read-only */
            return false;
        }
        case 1:  return priv;
        case 2:  return priv || !write;
        default: return true;
    }
}

/* Under XP+FA, AP[0] normally becomes the hardware-managed access flag. The
 * ARM1176 preserves one deprecated compatibility corner: APX:AP==000 with
 * exactly one of SCTLR.S/R set still uses the legacy read-only permissions. */
static bool access_flag_faults(const arm_cpu_t *c, bool xp,
                               unsigned ap, bool apx) {
    if (!xp || (c->cp15.sctlr & ARM_SCTLR_FA) == 0u || (ap & 1u) != 0u)
        return false;
    if (!apx && ap == 0u) {
        bool s = (c->cp15.sctlr & ARM_SCTLR_S) != 0u;
        bool r = (c->cp15.sctlr & ARM_SCTLR_R) != 0u;
        if (s != r) return false;
    }
    return true;
}

/*
 * XN — execute never. ARMv6 puts it in bit 4 of a section or supersection, bit
 * 15 of a large page and bit 0 of a small page, and it exists only when
 * SCTLR.XP selects the extended descriptor format (with XP clear those bits
 * mean something else entirely, so reading them as XN would invent faults).
 *
 * This is not theoretical for xnu-1357.5.30. The kernel really does set it:
 *
 *   _nx_enabled   0xc020e1b8  a __DATA global holding 1 in the image on disk.
 *                             Only four things reference it: _pmap_enter,
 *                             _pmap_protect and _pmap_page_protect, which all
 *                             just read it, and a name/pointer table entry at
 *                             0xc02434d0 that exposes it as a tunable. No code
 *                             writes it, and no boot-arg parse feeds it, so for
 *                             this boot it is 1.
 *   _pmap_enter   0xc006056c  Thumb. At +0x18 it tests prot & VM_PROT_EXECUTE;
 *                             if the mapping is NOT executable it falls through
 *                             to +0x1f8, which loads _nx_enabled and then
 *                             pmap->nx_enabled (the word at pmap+0x420) and,
 *                             when both are non-zero, sets r10 = 1. The PTE
 *                             template is built at +0x92 as "pa | 2" — a small
 *                             page with XN clear. +0x1f4 is reached only when
 *                             r10 == 1 and does "ORRS r2,r1" with r1 == r10:
 *                             "pa | 3", the small-page descriptor WITH XN set.
 *   _pmap_disable_NX 0xc005fe44  Thumb, five instructions: it stores 0 to
 *                             pmap+0x420, i.e. the per-pmap flag above. That is
 *                             the only opt-out, and it is per address space.
 *
 * So this kernel really does mark non-executable mappings XN for any address
 * space that has not opted out: the check below is live, not a rule invented
 * from the ARM ARM and never exercised. Enforcing it turns "branched into the
 * heap" from silently executing garbage into a prefetch abort at a known PC,
 * which is what the kernel's own SIGSEGV path expects to see.
 *
 * It is still correct if a configuration turns NX off — nothing then sets the
 * bit and nothing here fires — so the check costs nothing where it does not
 * apply.
 *
 * A manager domain (DACR == 0b11) skips the check, exactly as it skips the AP
 * check: the ARM ARM defines a manager domain as one where no permission fault
 * can be generated, and XN violations are reported as permission faults.
 */
static bool xn_forbids_fetch(const arm_cpu_t *c, arm_access_t acc, unsigned dac,
                             bool xn) {
    return acc == ARM_ACCESS_FETCH && xn && dac != 3u
        && (c->cp15.sctlr & ARM_SCTLR_XP) != 0u;
}

/*
 * Always inlined. It has two callers, the TLB-miss path below and ATS
 * (arm_mmu_ats); with two, the compiler stops inlining it into the miss path
 * on its own, and the call cost +0.56% host instructions on cpubench's mmu
 * workload (cachegrind, interp, ARM, user mode). ATS is rare, so the copy it
 * gets costs nothing that matters.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MMU_ALWAYS_INLINE inline __attribute__((always_inline))
#else
#define MMU_ALWAYS_INLINE inline
#endif
static MMU_ALWAYS_INLINE uint32_t mmu_walk(arm_cpu_t *c, uint32_t va,
                                           arm_access_t acc, bool priv,
                                           uint32_t *pa, bool *super);

static inline uint32_t mmu_tlb_tag(uint32_t va, arm_access_t acc,
                                   bool priv) {
    return ((va >> 10) << 3) | ((uint32_t)acc << 1) |
           (priv ? 1u : 0u);
}

static inline unsigned mmu_tlb_slot(uint32_t va, arm_access_t acc) {
    return ((va >> 10) + (unsigned)acc * (ARM_TLB_ENTRIES / 4u)) &
           (ARM_TLB_ENTRIES - 1u);
}

static bool mmu_stamp_matches(const arm_cpu_t *c) {
    return c && c->tlb_stamp.sctlr == c->cp15.sctlr &&
           c->tlb_stamp.ttbr0 == c->cp15.ttbr0 &&
           c->tlb_stamp.ttbr1 == c->cp15.ttbr1 &&
           c->tlb_stamp.ttbcr == c->cp15.ttbcr &&
           c->tlb_stamp.dacr == c->cp15.dacr &&
           c->tlb_stamp.context_id == c->cp15.context_id;
}

/*
 * Flush is a generation bump, not a memset. The guest flushes on every context
 * switch -- pmap_switch writes TTBR0 -- so an O(entries) flush would put a
 * 48 KB clear on a path the kernel takes constantly, and hand back much of
 * what the cache saves. Wraparound is the one case that must still clear:
 * after 2^32 flushes generation 0 would match stale entries left from the
 * very first one.
 */
void arm_mmu_tlb_flush(arm_cpu_t *c) {
    if (!c) return;
    c->tlb_flushes++;
    /*
     * The fetch-block cache dies with the TLB. It carries its own generation,
     * so the compare below would usually catch this -- but the wrap path in
     * this very function resets tlb_gen to 1, and an entry filled under an
     * earlier generation 1 would then match a stale block. Clearing the
     * pointer is unconditional and costs nothing next to a flush.
     */
    c->fetch_host = NULL;
    if (++c->tlb_gen == 0u) {
        memset(c->tlb, 0, sizeof c->tlb);
        /*
         * The data block caches die here too, and ONLY here. They carry a
         * generation like the TLB, so an ordinary flush costs them nothing --
         * but this wrap resets tlb_gen to 1, and an entry filled under an
         * earlier generation 1 would match a stale block. The fetch cache
         * clears its single pointer on every flush because that is free; a
         * 1 KB array is not, and a flush happens on every context switch.
        */
        memset(c->dread, 0, sizeof c->dread);
        memset(c->dwrite, 0, sizeof c->dwrite);
        c->tlb_gen = 1u;
    }
}

/*
 * The cached front end. A hit must be indistinguishable from a walk -- same
 * physical address, same fault code -- or something will eventually depend on
 * the difference and be impossible to find.
 *
 * The MMU-off case is deliberately NOT cached. It is already a single compare
 * and an assignment, and caching it would mean flushing on the SCTLR.M edge
 * for no gain.
 */
void arm_mmu_sync_stamp(arm_cpu_t *c) {
    if (!c || !(c->cp15.sctlr & ARM_SCTLR_M)) return;
    if (c->tlb_gen == 0u) c->tlb_gen = 1u;
    if (!mmu_stamp_matches(c)) {
        arm_mmu_tlb_flush(c);
        c->tlb_stamp.sctlr      = c->cp15.sctlr;
        c->tlb_stamp.ttbr0      = c->cp15.ttbr0;
        c->tlb_stamp.ttbr1      = c->cp15.ttbr1;
        c->tlb_stamp.ttbcr      = c->cp15.ttbcr;
        c->tlb_stamp.dacr       = c->cp15.dacr;
        c->tlb_stamp.context_id = c->cp15.context_id;
    }
}

uint32_t arm_mmu_translate(arm_cpu_t *c, uint32_t va, arm_access_t acc,
                           bool priv, uint32_t *pa) {
    if (!(c->cp15.sctlr & ARM_SCTLR_M)) { *pa = va; return 0; }

    /*
     * GENERATION 0 MEANS "NOT INITIALISED", and it must never match.
     *
     * arm_reset() sets this to 1, but plenty of code makes an arm_cpu_t by
     * zeroing memory instead -- both memory-disk bridge fixtures do exactly
     * that, and so would any future caller. A zeroed struct has tlb_gen 0 AND
     * every entry at generation 0, so without this the empty table reads as
     * 4096 valid translations of virtual zero. It cost two test suites to
     * find; fixing it here rather than in the callers means it cannot come
     * back through a caller nobody has written yet.
     */
    if (c->tlb_gen == 0u) c->tlb_gen = 1u;

    /* Every cached entry is valid only under the registers it was walked
     * under. See tlb_stamp: this catches a change made by any route, not just
     * by MCR, which is what keeps direct mutation from reading stale. */
    if (!mmu_stamp_matches(c)) {
        arm_mmu_tlb_flush(c);
        c->tlb_stamp.sctlr      = c->cp15.sctlr;
        c->tlb_stamp.ttbr0      = c->cp15.ttbr0;
        c->tlb_stamp.ttbr1      = c->cp15.ttbr1;
        c->tlb_stamp.ttbcr      = c->cp15.ttbcr;
        c->tlb_stamp.dacr       = c->cp15.dacr;
        c->tlb_stamp.context_id = c->cp15.context_id;
    }

    /* 1 KB key: see ARM_TLB_ENTRIES for why it cannot be the 4 KB page. */
    const uint32_t tag = mmu_tlb_tag(va, acc, priv);
    /*
     * THE INDEX MUST SEPARATE WHAT THE TAG SEPARATES.
     *
     * This was `(va >> 10) & (ARM_TLB_ENTRIES - 1u)`, which ignores `acc`
     * while the tag above includes it. So a FETCH and a data READ of the same
     * 1 KB region hash to one slot, carry different tags, and evict each
     * other -- every time, forever, in a direct-mapped table.
     *
     * Thumb is 68.95% of retired instructions and `LDR Rd,[PC,#imm8*4]` has a
     * 0-1020 byte reach, so a large share of literal-pool loads land in the
     * very block their code is executing from. Each one costs two walks: the
     * load evicts the fetch entry, then the next fetch evicts the load's.
     *
     * Offsetting each access class by a quarter of the table keeps the full
     * virtual-address entropy within a class while giving the three classes
     * disjoint regions. Purely an index change -- the tag at `tag` above
     * already carries `acc`, so no hit that was correct can become incorrect
     * and no fault behaviour moves. It is a cache; only eviction changes.
     */
    const unsigned slot = mmu_tlb_slot(va, acc);

    /*
     * A FAULTING TRANSLATION MUST LEAVE *pa UNTOUCHED, on a hit exactly as on
     * a walk. The walk returns before assigning it, and callers rely on that:
     * test_mmu_ttbcr_pd_bits_suppress_selected_walk seeds 0xdeadbeef and
     * checks it survives a PD0 fault. A first draft assigned unconditionally
     * and turned that into a zero, which is the kind of difference between a
     * hit and a miss that this cache exists to never have.
     */
    if (c->tlb[slot].gen == c->tlb_gen && c->tlb[slot].tag == tag) {
        c->tlb_hits++;
        if (c->tlb[slot].fsr == 0u) *pa = c->tlb[slot].pa | (va & 0x3ffu);
        return c->tlb[slot].fsr;
    }

    c->tlb_misses++;
    /* Straight into the caller's pa, so the untouched-on-fault contract is the
     * walk's own rather than something restated here. */
    uint32_t fsr = mmu_walk(c, va, acc, priv, pa, NULL);
    c->tlb[slot].gen = c->tlb_gen;
    c->tlb[slot].tag = tag;
    c->tlb[slot].fsr = fsr;
    c->tlb[slot].pa  = (fsr == 0u) ? (*pa & ~0x3ffu) : 0u;
    return fsr;
}

bool arm_fetch_cache_try_refill(arm_cpu_t *c, uint32_t va, bool priv) {
    uint32_t pa_block;
    const uint32_t va_block = va & ~UINT32_C(0x3ff);
    bool count_tlb_hit = false;

    if (!c || !c->bus || !c->bus->host_ram) return false;
    if (c->fetch_host && c->fetch_blk == va_block &&
        c->fetch_gen == c->tlb_gen && c->fetch_priv == priv)
        return true;

    if ((c->cp15.sctlr & ARM_SCTLR_M) == 0u) {
        pa_block = va_block;
    } else {
        const uint32_t tag =
            mmu_tlb_tag(va, ARM_ACCESS_FETCH, priv);
        const unsigned slot = mmu_tlb_slot(va, ARM_ACCESS_FETCH);
        if (c->tlb_gen == 0u || !mmu_stamp_matches(c) ||
            c->tlb[slot].gen != c->tlb_gen ||
            c->tlb[slot].tag != tag || c->tlb[slot].fsr != 0u)
            return false;
        pa_block = c->tlb[slot].pa;
        count_tlb_hit = true;
    }

    uint8_t *host = c->bus->host_ram(c->bus->ctx, pa_block, 0x400u);
    if (!host) return false;
    c->fetch_host = host;
    c->fetch_blk = va_block;
    c->fetch_gen = c->tlb_gen;
    c->fetch_priv = priv;
    if (count_tlb_hit) c->tlb_hits++;
    return true;
}

/* *super, when asked for, is set on success: whether the translation came
 * from a supersection, which ATS reports (PAR.SS). */
static MMU_ALWAYS_INLINE uint32_t mmu_walk(arm_cpu_t *c, uint32_t va,
                                           arm_access_t acc, bool priv,
                                           uint32_t *pa, bool *super) {
    /* Only a store sets WnR. A fetch is checked against XN, never against WnR:
     * IFSR has no such field. */
    bool write = (acc == ARM_ACCESS_WRITE);

    /* MMU disabled: physical == virtual. This is how every boot ROM starts. */
    if (!(c->cp15.sctlr & ARM_SCTLR_M)) { *pa = va; return 0; }

    /* --- first level ---------------------------------------------------------
     * ARMv6 TTBCR.N splits translation between TTBR0 and TTBR1. When the top N
     * bits of the VA are zero the walk starts from TTBR0 (whose table shrinks to
     * 2^(14-N) bytes and is indexed by VA[31-N:20]); otherwise it starts from
     * TTBR1, always a full 16 KB table indexed by VA[31:20].
     *
     * This is not optional bookkeeping. XNU-ARM on the ARM1176 runs with N=2, so
     * everything at and above 0x40000000 — all of kernel text and the 0xffff0000
     * exception-vector page — resolves through TTBR1, while TTBR0 holds the
     * *current user* pmap. Walking TTBR0 unconditionally happens to work only
     * while TTBR0 still maps kernel space; the first time the kernel loads a user
     * pmap into TTBR0 (pmap_switch calling set_mmu_ttb), kernel text and the
     * vector page disappear from the walk and the CPU storms forever on prefetch
     * aborts at 0xffff000c. Honouring N/TTBR1 is what keeps the kernel mapped
     * across that switch. */
    unsigned ttbcr_n = c->cp15.ttbcr & 7u;
    bool use_ttbr0 = ttbcr_n == 0u || (va >> (32u - ttbcr_n)) == 0u;
    uint32_t l1_addr;
    if (use_ttbr0) {
        uint32_t base = c->cp15.ttbr0 & (0xffffffffu << (14u - ttbcr_n));
        uint32_t idx  = (va >> 20) & ((1u << (12u - ttbcr_n)) - 1u);
        l1_addr = base | (idx << 2);
    } else {
        l1_addr = (c->cp15.ttbr1 & 0xffffc000u) | ((va >> 20) << 2);
    }

    /* TTBCR.PD0/PD1 disable the selected table walk. The architected result
     * is a section translation fault without reading even the first-level
     * descriptor. This ordering matters when the table address aliases MMIO:
     * a disabled walk must not trigger a device read as a side effect. */
    unsigned pd_bit = use_ttbr0 ? 4u : 5u;
    if ((c->cp15.ttbcr & (1u << pd_bit)) != 0u)
        return fsr_make(ARM_FSR_SECTION_TRANSLATION, 0, write);

    uint32_t l1      = c->bus->read32(c->bus->ctx, l1_addr);
    unsigned type    = l1 & 3u;
    unsigned domain  = (l1 >> 5) & 0xfu;
    bool xp = (c->cp15.sctlr & ARM_SCTLR_XP) != 0u;

    if (type == 0) return fsr_make(ARM_FSR_SECTION_TRANSLATION, 0, write);

    /* ARM1176 removes the obsolete fine-page-table descriptor. L1 type 3 is a
     * section translation fault in both XP formats, and that classification
     * precedes the domain lookup. Treating it as a page-table pointer long
     * enough to consult DACR can turn malformed guest tables into the wrong
     * exception and send an OS fault handler down an unrecoverable path. */
    if (type == 3u)
        return fsr_make(ARM_FSR_SECTION_TRANSLATION, 0, write);

    /* Supersections always belong to domain zero. Bits [8:5] are not a domain
     * in that descriptor format (some are extended PA bits on implementations
     * wider than 32 bits), so using them can spuriously deny a valid mapping. */
    bool supersection = type == 2u && ((l1 >> 18) & 1u) != 0u;
    if (supersection) domain = 0u;

    unsigned dac = (c->cp15.dacr >> (domain * 2u)) & 3u;

    if (type == 2u) {                       /* section or supersection */
        unsigned ap = (l1 >> 10) & 3u;
        /* Bit 15 is APX only in the XP=1 extended descriptor. With XP clear it
         * is not a permission bit and must not make a writable section RO. */
        bool apx = xp && ((l1 >> 15) & 1u) != 0u;
        /* With XP+FA, AP[0] is an access flag. Its fault outranks both domain
         * and ordinary AP permission checks, including a Manager domain. The
         * deprecated opposite-S/R AP=000 exception is handled by the helper. */
        if (access_flag_faults(c, xp, ap, apx))
            return fsr_make(ARM_FSR_SECTION_ACCESS_FLAG, domain, write);

        /* 00 = no access, 01 = client (check AP), 10 = reserved,
         * 11 = manager. A section has no second descriptor to classify, so
         * its domain check happens immediately. */
        if (dac == 0u || dac == 2u)
            return fsr_make(ARM_FSR_SECTION_DOMAIN, domain, write);
        if (dac != 3u && !ap_permits(c, ap, apx, write, priv))
            return fsr_make(ARM_FSR_SECTION_PERMISSION, domain, write);
        /* Sections and supersections both carry XN in bit 4. */
        if (xn_forbids_fetch(c, acc, dac, (l1 >> 4) & 1u))
            return fsr_make(ARM_FSR_SECTION_PERMISSION, domain, false);

        /*
         * Bit 18 selects a 16 MB supersection, which takes its base from
         * bits[31:24] and the offset from va[23:0] — a different split from the
         * 1 MB section. Treating a supersection as a section silently resolves
         * the wrong physical address, which is exactly how a real XNU kernel
         * ended up reading garbage where a valid pointer lived.
         */
        if (supersection)
            *pa = (l1 & 0xff000000u) | (va & 0x00ffffffu);
        else
            *pa = (l1 & 0xfff00000u) | (va & 0x000fffffu);
        if (super) *super = supersection;
        return 0;
    }

    if (type == 1u) {                       /* coarse second-level table */
        uint32_t l2_addr = (l1 & 0xfffffc00u) | (((va >> 12) & 0xffu) << 2);
        uint32_t l2      = c->bus->read32(c->bus->ctx, l2_addr);
        unsigned t2      = l2 & 3u;

        if (t2 == 0u) return fsr_make(ARM_FSR_PAGE_TRANSLATION, domain, write);

        unsigned ap;
        bool apx;
        if (xp) {
            /* Revised ARMv6 descriptors use one AP field for the whole page. */
            ap = (l2 >> 4) & 3u;
            apx = ((l2 >> 9) & 1u) != 0u;
        } else if (t2 == 1u) {
            /* Backwards-compatible 64 KB pages have four 16 KB AP subpages,
             * selected by VA[15:14]. */
            unsigned subpage = (va >> 14) & 3u;
            ap = (l2 >> (4u + subpage * 2u)) & 3u;
            apx = false;
        } else if (t2 == 2u) {
            /* Backwards-compatible 4 KB pages have four 1 KB AP subpages,
             * selected by VA[11:10]. */
            unsigned subpage = (va >> 10) & 3u;
            ap = (l2 >> (4u + subpage * 2u)) & 3u;
            apx = false;
        } else {
            /* Type 3 is the backwards-compatible extended-small-page form. It
             * has a single AP field and no APX or XN bit when XP is clear. */
            ap = (l2 >> 4) & 3u;
            apx = false;
        }

        /* The extended page descriptor's AP[0] access flag has the same
         * priority over DACR and AP permission as its section counterpart. */
        if (access_flag_faults(c, xp, ap, apx))
            return fsr_make(ARM_FSR_PAGE_ACCESS_FLAG, domain, write);

        /* Page translation faults have higher priority than domain faults.
         * The page domain is checked only after the second-level descriptor
         * has been returned and classified (ARM1176 TRM 6.9.5/Table 6-11). */
        if (dac == 0u || dac == 2u)
            return fsr_make(ARM_FSR_PAGE_DOMAIN, domain, write);

        if (dac != 3u && !ap_permits(c, ap, apx, write, priv))
            return fsr_make(ARM_FSR_PAGE_PERMISSION, domain, write);
        /* A large page keeps XN in bit 15; a small page has it in bit 0, which
         * is why t2 == 3 and t2 == 2 are the same descriptor type. */
        if (xn_forbids_fetch(c, acc, dac, (t2 == 1u) ? ((l2 >> 15) & 1u) : (l2 & 1u)))
            return fsr_make(ARM_FSR_PAGE_PERMISSION, domain, false);

        if (t2 == 1u) *pa = (l2 & 0xffff0000u) | (va & 0x0000ffffu); /* 64 KB */
        else          *pa = (l2 & 0xfffff000u) | (va & 0x00000fffu); /* 4 KB  */
        if (super) *super = false;
        return 0;
    }

    /* Kept as a defensive fallback if the decoder above gains another type. */
    return fsr_make(ARM_FSR_SECTION_TRANSLATION, domain, write);
}

/*
 * ATS1C*: see arm.h. A walk rather than a TLB lookup, because the TLB keeps
 * no page size and PAR.SS needs one; the TLB is only ever allowed to return
 * what a walk would, so the answer is the same. The walk's fault is the
 * DFSR value the access would have raised, reshaped into PAR's fault form.
 */
uint32_t arm_mmu_ats(arm_cpu_t *c, uint32_t va, bool write, bool priv) {
    if (!(c->cp15.sctlr & ARM_SCTLR_M)) return va & 0xfffff000u;
    uint32_t pa = 0;
    bool super = false;
    const uint32_t fsr = mmu_walk(c, va, write ? ARM_ACCESS_WRITE : ARM_ACCESS_READ,
                                  priv, &pa, &super);
    if (fsr != 0u)
        return 1u | ((fsr & 0xfu) << 1) | (((fsr >> 10) & 1u) << 5)
                  | (((fsr >> 12) & 1u) << 6);
    return super ? (pa & 0xff000000u) | 2u : pa & 0xfffff000u;
}
