#!/usr/bin/env python3
"""Build the guest CPU benchmark images and emit them as a C header.

    python3 tools/gen_guest_bench.py            # regenerate the header
    python3 tools/gen_guest_bench.py --check    # fail if it is stale

The header (bench/guest/generated/guest_images.h) is committed, so building
and running the benchmarks needs no ARM toolchain -- in particular not on
Windows. Regenerating needs Clang with the ARM target, ld.lld and
llvm-objcopy/llvm-nm (any recent LLVM; 18 was used).

Three images are produced from the same sources (bench/guest/*):
  arm     ARM1176: workloads compiled -marm, VFPv2 hard-float (the vfp
          workload runs)
  thumb   ARM1176: workloads compiled -mthumb (Thumb-1: the ARM1176 has no
          Thumb-2), soft-float ABI; vfp is compiled out and returns 0 here
  thumb2  Cortex-A8 (ARMv7-A): workloads compiled -mthumb, so Thumb-2 with
          IT blocks, CBZ, TBB/TBH and the wide encodings; VFPv2 hard-float,
          which is VFP in Thumb state. Runs on the ARM_ARCH_V7_A8 profile.
start.S (vectors, startup, SVC handler) is ARM state in all three.

The header records the SHA-256 of every input, of the compiler flags, and the
tool versions, and --check recomputes the digest, so a stale image is detected
even on a machine that cannot rebuild it.
"""
import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "bench", "guest")
OUT = os.path.join(SRC, "generated", "guest_images.h")
INPUTS = ["start.S", "runtime.c", "workloads.c", "workloads.h", "link.ld"]
SYMBOLS = ["_start", "mbox", "svc_counter", "fiq_counter", "wl_arena", "__bss_end"]

ARMV6 = ["--target=armv6kz-none-eabi", "-mcpu=arm1176jzf-s"]
ARMV7 = ["--target=armv7a-none-eabi", "-mcpu=cortex-a8"]
COMMON = ["-O2", "-ffreestanding", "-fno-builtin", "-nostdlib", "-fno-pic",
          "-fno-strict-aliasing", "-ffp-contract=off", "-fno-math-errno",
          "-fno-exceptions", "-fno-unwind-tables",
          "-fno-asynchronous-unwind-tables", "-Wall", "-Wextra", "-Werror"]
# Per image: (target flags, instruction-set flags for the C sources). The
# Cortex-A8's own FPU is VFPv3 with NEON; -mfpu=vfpv2 keeps the compiler to
# the VFP encodings this emulator implements (vfp.c: VFPv2, d0-d15).
ISAS = {
    "arm":    (ARMV6, ["-marm", "-mfloat-abi=hard", "-mfpu=vfpv2"]),
    "thumb":  (ARMV6, ["-mthumb", "-mfloat-abi=soft"]),
    "thumb2": (ARMV7, ["-mthumb", "-mfloat-abi=hard", "-mfpu=vfpv2"]),
}


def tool(names):
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    sys.exit("error: none of %s found on PATH" % ", ".join(names))


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("error: %s\n%s%s" % (" ".join(cmd), r.stdout, r.stderr))
    return r.stdout


def input_digest():
    h = hashlib.sha256()
    for name in INPUTS:
        with open(os.path.join(SRC, name), "rb") as f:
            data = f.read().replace(b"\r\n", b"\n")
        h.update(name.encode() + b"\0" + data + b"\0")
    h.update(repr((COMMON, sorted(ISAS.items()))).encode())
    return h.hexdigest()


def build(isa, tmp, cc, ld, objcopy, nm):
    objs = []
    start_o = os.path.join(tmp, isa + "_start.o")
    target, flags = ISAS[isa]
    run([cc] + target + COMMON + ["-marm", "-c", os.path.join(SRC, "start.S"),
                                  "-o", start_o])
    objs.append(start_o)
    for c in ("runtime.c", "workloads.c"):
        o = os.path.join(tmp, "%s_%s.o" % (isa, c[:-2]))
        run([cc] + target + COMMON + flags + ["-c", os.path.join(SRC, c), "-o", o])
        objs.append(o)
    elf = os.path.join(tmp, isa + ".elf")
    run([ld, "-T", os.path.join(SRC, "link.ld"), "--no-undefined",
         "-o", elf] + objs)
    binf = os.path.join(tmp, isa + ".bin")
    run([objcopy, "-O", "binary", elf, binf])
    with open(binf, "rb") as f:
        image = f.read()
    syms = {}
    for line in run([nm, elf]).splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] in SYMBOLS:
            syms[parts[2]] = int(parts[0], 16)
    missing = [s for s in SYMBOLS if s not in syms]
    if missing:
        sys.exit("error: %s image lacks symbols %s" % (isa, missing))
    return image, syms


def emit(images, digest, versions):
    lines = [
        "/* GENERATED by tools/gen_guest_bench.py -- do not edit. */",
        "/* inputs-sha256: %s */" % digest,
    ]
    for v in versions:
        lines.append("/* tool: %s */" % v)
    lines += [
        "#ifndef S5LBOX_GUEST_IMAGES_H",
        "#define S5LBOX_GUEST_IMAGES_H",
        "#include <stdint.h>",
        '#define GUEST_BENCH_INPUTS_SHA256 "%s"' % digest,
    ]
    for isa, (image, syms) in images.items():
        up = isa.upper()
        lines.append("#define GUEST_BENCH_%s_SIZE %du" % (up, len(image)))
        for s in SYMBOLS:
            macro = re.sub(r"[^A-Za-z0-9]", "", s).upper()
            lines.append("#define GUEST_BENCH_%s_%s 0x%08xu" % (up, macro, syms[s]))
        lines.append("static const uint8_t guest_bench_%s_image[%d] = {" % (isa, len(image)))
        for i in range(0, len(image), 16):
            chunk = image[i:i + 16]
            lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
        lines.append("};")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed header matches the inputs")
    args = ap.parse_args()
    digest = input_digest()
    if args.check:
        try:
            with open(OUT) as f:
                head = f.read(4096)
        except OSError:
            sys.exit("error: %s missing" % OUT)
        m = re.search(r"inputs-sha256: ([0-9a-f]{64})", head)
        if not m or m.group(1) != digest:
            sys.exit("error: %s is stale; run tools/gen_guest_bench.py" % OUT)
        print("guest_images.h is current (%s)" % digest)
        return
    cc = tool(["clang"])
    ld = tool(["ld.lld"])
    objcopy = tool(["llvm-objcopy"])
    nm = tool(["llvm-nm"])
    versions = [run([cc, "--version"]).splitlines()[0],
                run([ld, "--version"]).splitlines()[0]]
    with tempfile.TemporaryDirectory() as tmp:
        images = {isa: build(isa, tmp, cc, ld, objcopy, nm) for isa in ISAS}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write(emit(images, digest, versions))
    for isa, (image, syms) in images.items():
        print("%-6s %7d bytes  entry 0x%08x  mbox 0x%08x  bss_end 0x%08x"
              % (isa, len(image), syms["_start"], syms["mbox"], syms["__bss_end"]))
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
